<<<<<<< HEAD
# Generated by Django 5.2 on 2025-07-09 23:33
=======
# Generated by Django 5.2 on 2025-07-01 09:37
>>>>>>> 3da9a24fed32cd4ff816f1cc31908e8e39f2cc4a

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название сайта')),
                ('description', models.TextField(verbose_name='Описание сайта')),
<<<<<<< HEAD
                ('logo', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='logo/', verbose_name='Логотип')),
                ('icon', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='icon/', verbose_name='Иконка')),
=======
                ('logo', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='logo/', verbose_name='Логотип')),
>>>>>>> 3da9a24fed32cd4ff816f1cc31908e8e39f2cc4a
                ('locate', models.CharField(max_length=100, verbose_name='Адрес')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('work_schedule', models.CharField(max_length=100, verbose_name='Режим работы')),
                ('whatsapp', models.URLField(verbose_name='Whatsapp')),
                ('telegram', models.URLField(verbose_name='Telegram')),
                ('instagram', models.URLField(verbose_name='Instagram')),
                ('facebook', models.URLField(verbose_name='Facebook')),
            ],
            options={
                'verbose_name': '1) Настройки',
                'verbose_name_plural': '1) Настройки',
            },
        ),
<<<<<<< HEAD
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название слайда')),
                ('title_2', models.CharField(max_length=100, verbose_name='Название слайда под желтым')),
                ('description', models.TextField(verbose_name='Описание слайда')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='slides/', verbose_name='Изображение')),
                ('icon', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='slides/', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': '2) Слайды',
                'verbose_name_plural': '2) Слайды',
            },
        ),
=======
>>>>>>> 3da9a24fed32cd4ff816f1cc31908e8e39f2cc4a
    ]
