# Generated by Django 5.2 on 2025-07-13 10:12

import ckeditor_uploader.fields
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название статьи')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание статьи')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='blog/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': '2) Статьи',
                'verbose_name_plural': '2) Статьи',
            },
        ),
        migrations.AlterModelOptions(
            name='slide',
            options={'verbose_name': '3) Слайды', 'verbose_name_plural': '3) Слайды'},
        ),
    ]
