# Generated by Django 5.2 on 2025-07-03 18:00

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='icon',
            field=django_resized.forms.ResizedImageField(crop=None, default=1, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='icon/', verbose_name='Иконка'),
            preserve_default=False,
        ),
    ]
