# Generated by Django 5.2 on 2025-07-04 09:47

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_settings_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название слайда')),
                ('title_2', models.CharField(max_length=100, verbose_name='Название слайда под желтым')),
                ('description', models.TextField(verbose_name='Описание слайда')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='slides/', verbose_name='Изображение')),
                ('icon', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='slides/', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': '2) Слайды',
                'verbose_name_plural': '2) Слайды',
            },
        ),
    ]
