# Generated by Django 5.2 on 2025-07-22 23:46

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_blog_alter_slide_options'),
        ('extra', '0006_delete_serivicelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название Организации')),
                ('duration', models.CharField(max_length=100, verbose_name='Длительность')),
                ('price', models.CharField(max_length=100, verbose_name='Стоимость')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='process/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extra.ourservices', verbose_name='Категория')),
            ],
            options={
                'verbose_name': '4) Проекты',
                'verbose_name_plural': '4) Проекты',
            },
        ),
    ]
