# Generated by Django 5.2 on 2026-07-05 13:39

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='icon',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=85, scale=None, size=[1920, 1080], upload_to='slides/', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=85, scale=None, size=[1920, 1080], upload_to='slides/', verbose_name='Изображение'),
        ),
    ]
