# Generated by Django 5.0.7 on 2024-08-26 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': '3) Пользователь телеграм', 'verbose_name_plural': '3) Пользователи телеграма'},
        ),
    ]
