# Generated by Django 5.0.7 on 2024-11-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_alter_telegramuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramuser',
            options={},
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='chat_id',
            field=models.BigIntegerField(verbose_name='Чат ID'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='id_user',
            field=models.BigIntegerField(unique=True, verbose_name='ID пользователя Telegram'),
        ),
    ]
