# Generated by Django 5.0.7 on 2025-01-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0004_telegramadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramadmin',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата добавления администратора', verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='telegramadmin',
            name='chat_id',
            field=models.BigIntegerField(help_text='ID пользователя в Telegram', unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='telegramadmin',
            name='description',
            field=models.TextField(blank=True, help_text='Дополнительная информация об администраторе', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='telegramadmin',
            name='is_developer',
            field=models.BooleanField(default=False, help_text='Может ли пользователь управлять другими админами', verbose_name='Разработчик'),
        ),
        migrations.AlterField(
            model_name='telegramadmin',
            name='username',
            field=models.CharField(blank=True, help_text='Username пользователя в Telegram (без @)', max_length=100, null=True, verbose_name='Username'),
        ),
    ]
