# Generated by Django 5.2 on 2025-07-16 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0005_alter_telegramadmin_added_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramAdmin',
        ),
    ]
