version: '3.8'

services:
  db_kiki:
    image: postgres:14
    container_name: postgres_db_kiki
    env_file:
      - ../.env
    volumes:
      - postgres_data_kiki:/var/lib/postgresql/data
    networks:
      - portfolio_network_kiki
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis_kiki:
    image: redis:6
    container_name: redis_kiki
    networks:
      - portfolio_network_kiki

  web_kiki:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: django_web_kiki
    command: /entrypoint.sh gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 3 --threads 2 --timeout 60 --max-requests 500 --max-requests-jitter 50 --access-logfile -
    volumes:
      - ../app:/app
    env_file:
      - ../.env
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
    depends_on:
      db_kiki:
        condition: service_healthy
      redis_kiki:
        condition: service_started
    ports:
      - "8000:8000"
    networks:
      - portfolio_network_kiki

  telegram_bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: telegram_bot_kiki
    command: python manage.py bot
    volumes:
      - ../app:/app
    env_file:
      - ../.env
    depends_on:
      - db_kiki
      - web_kiki
    networks:
      - portfolio_network_kiki

networks:
  portfolio_network_kiki:
    driver: bridge

volumes:
  postgres_data_kiki:
