# Generated by Django 5.2 on 2025-07-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reviews/', verbose_name='Фото')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('service', models.CharField(max_length=50, verbose_name='Услуга')),
                ('description', models.TextField(verbose_name='Описание')),
                ('show', models.BooleanField(default=True, verbose_name='Отображать')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
