# Generated by Django 5.2 on 2025-07-14 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('extra', '0005_ourservices_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'verbose_name': '1) Отзыв', 'verbose_name_plural': '1) Отзывы'},
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='extra.ourservices', verbose_name='Услуга'),
        ),
    ]
