# Generated by Django 5.2 on 2025-07-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_testimonial_options_alter_testimonial_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='show',
            field=models.BooleanField(default=False, verbose_name='Отображать'),
        ),
    ]
