# Generated by Django 5.2 on 2025-07-16 18:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contactmessage'),
        ('extra', '0006_delete_serivicelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя заказчика')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('rooms', models.PositiveSmallIntegerField(verbose_name='Количество комнат')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='extra.ourservices', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': '3) Бронь / заказ',
                'verbose_name_plural': '3) Брони / заказы',
                'ordering': ['-created_at'],
            },
        ),
    ]
