# Generated by Django 5.2 on 2025-07-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='more',
            field=models.TextField(blank=True, verbose_name='Дополнительная информация'),
        ),
    ]
