# Generated by Django 5.2 on 2025-07-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to='about/', verbose_name='Изображение 1')),
                ('image_2', models.ImageField(upload_to='about/', verbose_name='Изображение 2')),
                ('image_3', models.ImageField(upload_to='about/', verbose_name='Изображение 3')),
                ('image_4', models.ImageField(upload_to='about/', verbose_name='Изображение 4')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
    ]
