# Generated by Django 5.2 on 2025-07-09 23:33

import ckeditor_uploader.fields
import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='about/', verbose_name='Изображение 1')),
                ('image_2', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='about/', verbose_name='Изображение 2')),
                ('image_3', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='about/', verbose_name='Изображение 3')),
                ('image_4', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='about/', verbose_name='Изображение 4')),
                ('title_1', models.CharField(max_length=100, verbose_name='Название 1')),
                ('title_2', models.CharField(max_length=100, verbose_name='Название c синим текстом')),
                ('description', models.TextField(verbose_name='Описание')),
                ('experience', models.CharField(max_length=100, verbose_name='Опыт')),
                ('customers', models.CharField(max_length=100, verbose_name='Дофольны Клиенты( в процентах )')),
                ('successfully', models.CharField(max_length=100, verbose_name='Успешно выполнено( в цифрах )')),
                ('time', models.CharField(max_length=100, verbose_name='Время работы')),
                ('number', models.CharField(max_length=100, verbose_name='Номер для связи')),
            ],
            options={
                'verbose_name': '1) О нас',
                'verbose_name_plural': '1) О нас',
            },
        ),
        migrations.CreateModel(
            name='BeforeAfter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('before_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='before_after/', verbose_name='Изображение до')),
                ('after_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='before_after/', verbose_name='Изображение после')),
                ('description', models.TextField(verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': '5) До и После',
                'verbose_name_plural': '5) До и После',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects_per_month', models.IntegerField(default=0, verbose_name='Проекты в месяц')),
                ('happy_customers', models.IntegerField(default=0, verbose_name='Довольные клиенты')),
                ('positive_reviews', models.IntegerField(default=0, verbose_name='Положительные отзывы')),
                ('cleaned_area_m2', models.IntegerField(default=0, verbose_name='Чистая площадь')),
            ],
            options={
                'verbose_name': '4) Мы в числах',
                'verbose_name_plural': '4) Мы в числах',
            },
        ),
        migrations.CreateModel(
            name='OurServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название Услуги')),
                ('subtitle', models.TextField(verbose_name='Подзаголовок Услуги')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание Услуги')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('icon', models.CharField(choices=[('icon-oosouji', 'Уборка'), ('icon-cleaning', 'Чистка'), ('icon-mop', 'Моп'), ('icon-vacuum', 'Пылесос'), ('icon-bucket', 'Ведро'), ('icon-sponge', 'Губка'), ('icon-broom', 'Метла'), ('icon-duster', 'Щетка'), ('icon-spray', 'Спрей'), ('icon-window', 'Окно'), ('icon-toilet', 'Туалет'), ('icon-kitchen', 'Кухня'), ('icon-bathroom', 'Ванная'), ('icon-carpet', 'Ковер'), ('icon-mattress', 'Матрас'), ('icon-furniture', 'Мебель'), ('icon-air', 'Воздух'), ('icon-laundry', 'Прачечная'), ('icon-disinfection', 'Дезинфекция'), ('icon-eco', 'Экологичность'), ('icon-quality', 'Качество')], max_length=50, verbose_name='Иконка Услуги')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='services/', verbose_name='Изображение Услуги')),
                ('banner_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='services/', verbose_name='Баннер Услуги')),
            ],
            options={
                'verbose_name': '2) Услуги',
                'verbose_name_plural': '2) Услуги',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Proccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название Процесса')),
                ('description', models.TextField(verbose_name='Описание Процесса')),
                ('icon', models.CharField(choices=[('icon-oosouji', 'Уборка'), ('icon-cleaning', 'Чистка'), ('icon-mop', 'Моп'), ('icon-vacuum', 'Пылесос'), ('icon-bucket', 'Ведро'), ('icon-sponge', 'Губка'), ('icon-broom', 'Метла'), ('icon-duster', 'Щетка'), ('icon-spray', 'Спрей'), ('icon-window', 'Окно'), ('icon-toilet', 'Туалет'), ('icon-kitchen', 'Кухня'), ('icon-bathroom', 'Ванная'), ('icon-carpet', 'Ковер'), ('icon-mattress', 'Матрас'), ('icon-furniture', 'Мебель'), ('icon-air', 'Воздух'), ('icon-laundry', 'Прачечная'), ('icon-disinfection', 'Дезинфекция'), ('icon-eco', 'Экологичность'), ('icon-quality', 'Качество')], max_length=50, verbose_name='Иконка Услуги')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': '3) Процесс',
                'verbose_name_plural': '3) Процессы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SeriviceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название Услуги')),
            ],
            options={
                'verbose_name': 'Список услуг',
                'verbose_name_plural': 'Список услуг',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='team/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': '5) Команда',
                'verbose_name_plural': '5) Команда',
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название миссии')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='extra.about')),
            ],
            options={
                'verbose_name': 'Миссия',
                'verbose_name_plural': 'Миссии',
            },
        ),
        migrations.CreateModel(
            name='ServicePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название пункта')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='extra.ourservices')),
            ],
            options={
                'verbose_name': 'Пункт услуги',
                'verbose_name_plural': 'Пункты услуги',
                'ordering': ['title'],
            },
        ),
    ]
