# Generated by Django 5.2 on 2025-07-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='title',
        ),
        migrations.AddField(
            model_name='about',
            name='customers',
            field=models.CharField(default=1, max_length=100, verbose_name='Дофольны Клиенты( в процентах )'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='experience',
            field=models.CharField(default=1, max_length=100, verbose_name='Опыт'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='number',
            field=models.CharField(default=1, max_length=100, verbose_name='Номер для связи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='successfully',
            field=models.CharField(default=1, max_length=100, verbose_name='Успешно выполнено( в цифрах )'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='time',
            field=models.CharField(default=1, max_length=100, verbose_name='Время работы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='title_1',
            field=models.CharField(default=1, max_length=100, verbose_name='Название 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='title_2',
            field=models.CharField(default=1, max_length=100, verbose_name='Название c синим текстом'),
            preserve_default=False,
        ),
    ]
