# Generated by Django 5.2 on 2025-07-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='experience',
            field=models.IntegerField(default=1, verbose_name='Опыт'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус'),
        ),
    ]
