# Generated by Django 5.2 on 2025-07-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0002_team_experience_team_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
    ]
