# Generated by Django 5.2 on 2025-07-05 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0002_remove_about_title_about_customers_about_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название миссии')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='extra.about')),
            ],
            options={
                'verbose_name': 'Миссия',
                'verbose_name_plural': 'Миссии',
            },
        ),
    ]
