# Generated by Django 5.2 on 2025-07-05 19:38

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0003_mission'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название Услуги')),
                ('subtitle', models.CharField(max_length=100, verbose_name='Подзаголовок Услуги')),
                ('description', models.TextField(verbose_name='Описание Услуги')),
                ('icon', models.CharField(choices=[('icon-oosouji', 'Уборка'), ('icon-cleaning', 'Чистка'), ('icon-mop', 'Моп'), ('icon-vacuum', 'Пылесос'), ('icon-bucket', 'Ведро'), ('icon-sponge', 'Губка'), ('icon-broom', 'Метла'), ('icon-duster', 'Щетка'), ('icon-spray', 'Спрей'), ('icon-window', 'Окно'), ('icon-toilet', 'Туалет'), ('icon-kitchen', 'Кухня'), ('icon-bathroom', 'Ванная'), ('icon-carpet', 'Ковер'), ('icon-mattress', 'Матрас'), ('icon-furniture', 'Мебель'), ('icon-air', 'Воздух'), ('icon-laundry', 'Прачечная'), ('icon-disinfection', 'Дезинфекция'), ('icon-eco', 'Экологичность'), ('icon-quality', 'Качество')], max_length=50, verbose_name='Иконка Услуги')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='services/', verbose_name='Изображение Услуги')),
            ],
            options={
                'verbose_name': 'Услуги',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.AlterField(
            model_name='about',
            name='image_1',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='about/', verbose_name='Изображение 1'),
        ),
        migrations.AlterField(
            model_name='about',
            name='image_2',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='about/', verbose_name='Изображение 2'),
        ),
        migrations.AlterField(
            model_name='about',
            name='image_3',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='about/', verbose_name='Изображение 3'),
        ),
        migrations.AlterField(
            model_name='about',
            name='image_4',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='about/', verbose_name='Изображение 4'),
        ),
    ]
