# Generated by Django 5.2 on 2025-07-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0003_alter_team_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourservices',
            name='price',
            field=models.CharField(default=1, help_text='Например: 5000', max_length=50, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ourservices',
            name='subtitle',
            field=models.CharField(max_length=100, verbose_name='Подзаголовок Услуги'),
        ),
    ]
