# Generated by Django 5.2 on 2025-07-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0004_ourservices_alter_about_image_1_alter_about_image_2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ourservices',
            options={'ordering': ['order'], 'verbose_name': 'Услуги', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AddField(
            model_name='ourservices',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
