# Generated by Django 5.2 on 2025-07-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0004_ourservices_price_alter_ourservices_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourservices',
            name='category',
            field=models.CharField(default=1, max_length=100, verbose_name='Категория Услуги'),
            preserve_default=False,
        ),
    ]
