# Generated by Django 5.2 on 2025-07-15 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0005_ourservices_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SeriviceList',
        ),
    ]
