# Generated by Django 5.2 on 2025-07-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0005_alter_ourservices_options_ourservices_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название Процесса')),
                ('description', models.TextField(verbose_name='Описание Процесса')),
                ('icon', models.CharField(choices=[('icon-oosouji', 'Уборка'), ('icon-cleaning', 'Чистка'), ('icon-mop', 'Моп'), ('icon-vacuum', 'Пылесос'), ('icon-bucket', 'Ведро'), ('icon-sponge', 'Губка'), ('icon-broom', 'Метла'), ('icon-duster', 'Щетка'), ('icon-spray', 'Спрей'), ('icon-window', 'Окно'), ('icon-toilet', 'Туалет'), ('icon-kitchen', 'Кухня'), ('icon-bathroom', 'Ванная'), ('icon-carpet', 'Ковер'), ('icon-mattress', 'Матрас'), ('icon-furniture', 'Мебель'), ('icon-air', 'Воздух'), ('icon-laundry', 'Прачечная'), ('icon-disinfection', 'Дезинфекция'), ('icon-eco', 'Экологичность'), ('icon-quality', 'Качество')], max_length=50, verbose_name='Иконка Услуги')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Процесс',
                'verbose_name_plural': 'Процессы',
                'ordering': ['order'],
            },
        ),
    ]
