# Generated by Django 5.2 on 2025-07-06 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0006_proccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriviceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название Услуги')),
            ],
            options={
                'verbose_name': '4) Лента услуги',
                'verbose_name_plural': '4) Лента услуг',
            },
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': '1) О нас', 'verbose_name_plural': '1) О нас'},
        ),
        migrations.AlterModelOptions(
            name='ourservices',
            options={'ordering': ['order'], 'verbose_name': '2) Услуги', 'verbose_name_plural': '2) Услуги'},
        ),
        migrations.AlterModelOptions(
            name='proccess',
            options={'ordering': ['order'], 'verbose_name': '3) Процесс', 'verbose_name_plural': '3) Процессы'},
        ),
    ]
