# Generated by Django 5.2 on 2025-07-06 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0007_serivicelist_alter_about_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': '4) Мы в числах',
                'verbose_name_plural': '4) Мы в числах',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='serivicelist',
            options={'verbose_name': '10) Лента услуги', 'verbose_name_plural': '10) Лента услуг'},
        ),
    ]
