# Generated by Django 5.2 on 2025-07-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0008_metric_alter_serivicelist_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metric',
            options={'verbose_name': '4) Мы в числах', 'verbose_name_plural': '4) Мы в числах'},
        ),
        migrations.RemoveField(
            model_name='metric',
            name='description',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='order',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='title',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='value',
        ),
        migrations.AddField(
            model_name='metric',
            name='cleaned_area_m2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metric',
            name='happy_customers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metric',
            name='positive_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metric',
            name='projects_per_month',
            field=models.IntegerField(default=0),
        ),
    ]
