# Generated by Django 5.2 on 2025-07-06 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0009_alter_metric_options_remove_metric_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='cleaned_area_m2',
            field=models.IntegerField(default=0, verbose_name='Чистая площадь'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='happy_customers',
            field=models.IntegerField(default=0, verbose_name='Довольные клиенты'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='positive_reviews',
            field=models.IntegerField(default=0, verbose_name='Положительные отзывы'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='projects_per_month',
            field=models.IntegerField(default=0, verbose_name='Проекты в месяц'),
        ),
    ]
