# Generated by Django 5.2 on 2025-07-07 07:59

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0010_alter_metric_cleaned_area_m2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='team/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': '5) Команда',
                'verbose_name_plural': '5) Команда',
            },
        ),
    ]
