# Generated by Django 5.2 on 2025-07-07 18:19

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0011_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourservices',
            name='banner_image',
            field=django_resized.forms.ResizedImageField(crop=None, default=1, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='services/', verbose_name='Баннер Услуги'),
            preserve_default=False,
        ),
    ]
