# Generated by Django 5.2 on 2025-07-07 18:50

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0012_ourservices_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourservices',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание Услуги'),
        ),
        migrations.AlterField(
            model_name='ourservices',
            name='subtitle',
            field=models.TextField(verbose_name='Подзаголовок Услуги'),
        ),
    ]
