# Generated by Django 5.2 on 2025-07-07 18:58

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0013_alter_ourservices_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourservices',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='ourservices',
            name='image',
        ),
        migrations.CreateModel(
            name='ServicePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=200, verbose_name='Пункт')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='services/', verbose_name='Изображение Услуги')),
                ('banner_image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='services/', verbose_name='Баннер Услуги')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='extra.ourservices')),
            ],
            options={
                'verbose_name': '2) Услуги',
                'verbose_name_plural': '2) Услуги',
                'ordering': ['order'],
            },
        ),
    ]
