# Generated by Django 5.2 on 2025-07-08 07:21

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0014_remove_ourservices_banner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourservices',
            name='banner_image',
            field=django_resized.forms.ResizedImageField(crop=None, default=1, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='services/', verbose_name='Баннер Услуги'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ourservices',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default=1, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='services/', verbose_name='Изображение Услуги'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ourservices',
            name='list_points',
            field=models.TextField(default=1, verbose_name='Список Услуги'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ServicePoint',
        ),
    ]
