# Generated by Django 5.2 on 2025-07-08 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0015_ourservices_banner_image_ourservices_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourservices',
            name='list_points',
        ),
        migrations.CreateModel(
            name='ServicePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название пункта')),
                ('description', models.TextField(verbose_name='Описание пункта')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='extra.ourservices')),
            ],
            options={
                'verbose_name': 'Пункт услуги',
                'verbose_name_plural': 'Пункты услуги',
                'ordering': ['title'],
            },
        ),
    ]
