# Generated by Django 5.2 on 2025-07-08 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0016_remove_ourservices_list_points_servicepoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepoint',
            name='description',
        ),
    ]
