# Generated by Django 5.2 on 2025-07-08 11:37

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0017_remove_servicepoint_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeforeAfter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('before_image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='before_after/', verbose_name='Фото до')),
                ('after_image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='before_after/', verbose_name='Фото после')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'До и после',
                'verbose_name_plural': 'До и после',
                'ordering': ['order'],
            },
        ),
    ]
