# Generated by Django 5.2 on 2025-07-08 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0018_beforeafter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beforeafter',
            options={'ordering': ['order'], 'verbose_name': 'До и После', 'verbose_name_plural': 'До и После'},
        ),
        migrations.AddField(
            model_name='beforeafter',
            name='description',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beforeafter',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='extra.ourservices', verbose_name='Услуга'),
        ),
    ]
