# Generated by Django 5.2 on 2025-07-08 11:53

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0019_alter_beforeafter_options_beforeafter_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beforeafter',
            options={'ordering': ['order'], 'verbose_name': '5) До и После', 'verbose_name_plural': '5) До и После'},
        ),
        migrations.AlterModelOptions(
            name='serivicelist',
            options={'verbose_name': 'Список услуг', 'verbose_name_plural': 'Список услуг'},
        ),
        migrations.RemoveField(
            model_name='beforeafter',
            name='service',
        ),
        migrations.AlterField(
            model_name='beforeafter',
            name='after_image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='before_after/', verbose_name='Изображение после'),
        ),
        migrations.AlterField(
            model_name='beforeafter',
            name='before_image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='before_after/', verbose_name='Изображение до'),
        ),
    ]
